title: Saidu Nazar
logo: "/git-dp.png?raw=true"
description: >  
  JavaScript Developer
  <br><br>
  <a href="https://www.linkedin.com/in/saidu-nazar/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
