title: <p align="center">Saidu Nazar</p>
logo: "/profile.png?raw=true"
description: > 
  Frontend Engineer | Learner
  <br><br>
  <a href="https://www.linkedin.com/in/saidu-nazar/">LinkedIn Profile</a>
  <br>
  <a href="">Gihub</a> 
theme: jekyll-theme-minimal
