title: Saidu Nazar
logo: "/profile.png?raw=true"
description: >  
  <br><br>
  Frontend Engineer | Learner
  <br><br>
  <a href="mailto:saidunazar92@gmail.com">Contact Me - Email</a>
  <br><br>
  <a href="https://www.linkedin.com/in/saidu-nazar/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
