title: <p align="center">Saidu Nazar</p>
logo: "/profile.png?raw=true"
 ### Frontend Engineer | Learner
description: >  
  <br><br>
  <a href="https://www.linkedin.com/in/saidu-nazar/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
